### ISSUE TITLE
Traduzir o padrão Iterator

### ISSUE THREAD

**Issue by diogomoreira** [design-patterns-for-humans/brazilian-portuguese#20]

**Comment by guilhermebferreira** [comment]
Posso contribuir com essa tradução.

**Comment by j-ew-s** [comment]
Se adicione no Assignees  e manda ver!

**Comment by guilhermebferreira** [comment]
Tive dificuldade com esse termo **“underlying presentation”**, que em tradução literal seria “apresentação subjacente”. Então olhei as outras opções de tradução das palavras de forma individual e tentei entender o sentido da frase (underlying: subjacente, de base, struturais; presentation: apresentação, quadro, entrega  ).

Acabei traduzindo **“...without exposing the underlying presentation.”** para **“...sem expor a toda a estrutura.”**
 
O trecho com o texto da wikipedia também possui alguns termos cuja tradução literal não funcionava bem, então minha fonte foi o artigo em pt-br da wikipédia tratando do assunto. Que possuía o mesmo parágrafo, só que com uma pequena modificação na ordem das frases, mas com o mesmo conteúdo.

**Comment by guilhermebferreira** [comment]
acho que seria bacana criar um CONTRIBUTING.md com algumas duvidas gerais...

Por exemplo: Nos exemplos programáticos, devo traduzir os nomes dos métodos, atributos e das classes, ou apenas traduzir os comentários?

**Comment by j-ew-s** [comment]
Boa!


________________________________
De: Guilherme Ferreira <notifications@github.com>
Enviado: segunda-feira, 9 de outubro de 2017 17:10
Para: design-patterns-for-humans/brazilian-portuguese
Cc: Gabriel Scavassa; Comment
Assunto: Re: [design-patterns-for-humans/brazilian-portuguese] Traduzir o padrão Iterator (#20)


acho que seria bacana criar um CONTRIBUTING.md com algumas duvidas gerais...

Por exemplo: Nos exemplos programáticos, devo traduzir os nomes dos métodos, atributos e das classes, ou apenas traduzir os comentários?
